### ISSUE TITLE
How do you handle testing?

### ISSUE THREAD

**Issue by nmstoker** [zanellia/prometeo#27]
Sorry if I've missed something, but is there a method you have to allow tests to run on the transpiled C to ensure it's working? (and presumably that it gives the same results as the python code, unless you've got some way of being 100% sure that is guaranteed due to your language restrictions)

**Comment by zanellia** [comment]
Hey @nmstoker I must have forgotten to reply to you, sorry for the loose response. For the moment I test locally and check on Travis CI installation, build and that examples and tests run successfully. I should implement some more systematic tests ASAP, i.g., based on dumping  numerical values at "checkpoints" to log files both with `--cgen=True` and `--cgen=False` and comparing the results.

**Comment by nmstoker** [comment]
Many thanks for the update!
