### ISSUE TITLE
Issue installing on Python 3.9.10

### ISSUE THREAD

**Issue by Hunter2809** [zanellia/prometeo#31]
Hi!
I was looking forward to installing the module but came across this error while trying to install the module on Python v3.9.10:
```bash
C:\Users\HP>py -3.9 -m pip install prometeo-dsl
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.6, <=3.9; 0.0.10 Requires-Python >=3.6, <=3.9; 0.0.2 Requires-Python >=3.6, <=3.9; 0.0.3 Requires-Python >=3.6, <=3.9; 0.0.4 Requires-Python >=3.6, <=3.9; 0.0.5 Requires-Python >=3.6, <=3.9; 0.0.6 Requires-Python >=3.6, <=3.9; 0.0.7 Requires-Python >=3.6, <=3.9; 0.0.9 Requires-Python >=3.6, <=3.9
ERROR: Could not find a version that satisfies the requirement prometeo-dsl (from versions: none)
ERROR: No matching distribution found for prometeo-dsl
```
The screenshot for the same:
![image](https://user-images.githubusercontent.com/46440327/168761640-f3268b4a-5bec-4e7b-b378-bf56a416af62.png)

**Comment by zanellia** [comment]
Hey @Hunter2807, thanks for you interest and thanks for reporting! Unfortunately there are small changes to the AST from one version to another which require small adjustments to prometeo. I have puhsed a fix regarding the handling of slice AST nodes. Will make a PyPI package for 3.9 later today/tomorrow.

**Comment by zanellia** [comment]
alright version 0.0.11 with beta support for Python3.9 is on PyPI https://pypi.org/project/prometeo-dsl/ - keep in mind that prometeo is still quite experimental: any feedback/suggestion is more than welcome!

**Comment by zanellia** [comment]
oh... I just noticed that you are using Windows... there is no support for Windows yet, but it should work with WSL.

**Comment by Hunter2809** [comment]
Ah, that explains the most of it. Thanks for telling! I might have missed that while reading the introduction 😅
